import type {
  EuSize,
  Product,
  ProductImage,
  ProductVariant,
} from "./types";

type VariantSeed = readonly [size: EuSize, inventoryQuantity: number];

function createVariants(
  productNumber: number,
  price: number,
  variants: readonly VariantSeed[],
): ProductVariant[] {
  return variants.map(([size, inventoryQuantity]) => {
    const sizeCode = String(size).replace(".", "5");
    const productCode = String(productNumber).padStart(2, "0");

    return {
      id: `demo-variant-${productCode}-${sizeCode}`,
      sku: `SVG-DEMO-${productCode}-${sizeCode}`,
      size,
      sizeLabel: `EU ${size}`,
      price,
      inventoryQuantity,
      availableForSale: inventoryQuantity > 0,
    };
  });
}

function createImage(
  productNumber: number,
  productTitle: string,
  colorway: string,
): ProductImage {
  const productCode = String(productNumber).padStart(2, "0");
  const demoImagePaths = [
    "/images/products/demo-court-bone.png",
    "/images/products/demo-terrace-forest.png",
    "/images/products/demo-runner-blue.png",
    "/images/products/demo-velocity-black.png",
  ] as const;

  return {
    id: `demo-image-${productCode}`,
    src: demoImagePaths[(productNumber - 1) % demoImagePaths.length],
    alt: `${productTitle} in ${colorway} — demo product image`,
  };
}

/**
 * Temporary catalog data for storefront development.
 *
 * Every record is fictional and marked with `isDemo: true`. Replace these
 * records with Shopify Storefront API data before launch.
 */
export const products = [
  {
    id: "demo-product-01",
    handle: "northline-apex-cloud",
    title: "Apex Cloud",
    brand: "Northline Studio",
    colorway: "Bone / Graphite",
    description:
      "A lightweight everyday silhouette with a layered upper, soft lining, and a sculpted sole built for long city days.",
    category: "Lifestyle",
    colors: [
      { name: "Bone", hex: "#E7E1D5" },
      { name: "Graphite", hex: "#343638" },
    ],
    tags: ["everyday", "neutral", "low-top"],
    currency: "GHS",
    price: 1290,
    images: [createImage(1, "Apex Cloud", "Bone / Graphite")],
    variants: createVariants(1, 1290, [
      [38, 2],
      [39, 3],
      [40, 4],
      [41, 2],
      [42, 5],
      [43, 1],
      [44, 0],
      [45, 2],
    ]),
    status: "active",
    isFeatured: true,
    isNewArrival: true,
    isDemo: true,
    publishedAt: "2026-07-24T09:00:00.000Z",
  },
  {
    id: "demo-product-02",
    handle: "aerial-pulse-runner",
    title: "Pulse Runner",
    brand: "Aerial Dept.",
    colorway: "Signal Orange / Chalk",
    description:
      "A breathable runner with responsive cushioning and high-contrast panels designed to bring energy to daily rotation.",
    category: "Running",
    colors: [
      { name: "Signal Orange", hex: "#F15A24" },
      { name: "Chalk", hex: "#F0EEE7" },
    ],
    tags: ["runner", "mesh", "bright"],
    currency: "GHS",
    price: 1450,
    images: [createImage(2, "Pulse Runner", "Signal Orange / Chalk")],
    variants: createVariants(2, 1450, [
      [37, 1],
      [38, 2],
      [39, 0],
      [40, 3],
      [41, 3],
      [42, 4],
      [43, 2],
      [44, 1],
    ]),
    status: "active",
    isFeatured: true,
    isNewArrival: true,
    isDemo: true,
    publishedAt: "2026-07-22T09:00:00.000Z",
  },
  {
    id: "demo-product-03",
    handle: "courtworks-arc-high",
    title: "Arc Court High",
    brand: "Courtworks",
    colorway: "Deep Green / Sail",
    description:
      "A supportive high-top inspired by indoor courts, finished with a padded collar and durable multi-surface outsole.",
    category: "Basketball",
    colors: [
      { name: "Deep Green", hex: "#18392B" },
      { name: "Sail", hex: "#ECE5D6" },
    ],
    tags: ["high-top", "court", "support"],
    currency: "GHS",
    price: 1690,
    images: [createImage(3, "Arc Court High", "Deep Green / Sail")],
    variants: createVariants(3, 1690, [
      [40, 2],
      [41, 1],
      [42, 3],
      [42.5, 2],
      [43, 4],
      [44, 2],
      [45, 1],
      [46, 0],
    ]),
    status: "active",
    isFeatured: true,
    isNewArrival: false,
    isDemo: true,
    publishedAt: "2026-07-12T09:00:00.000Z",
  },
  {
    id: "demo-product-04",
    handle: "northline-harbour-low",
    title: "Harbour Low",
    brand: "Northline Studio",
    colorway: "Ocean Blue / White",
    description:
      "A crisp low-profile sneaker with clean overlays, a stable cupsole, and an easy blue-and-white palette.",
    category: "Lifestyle",
    colors: [
      { name: "Ocean Blue", hex: "#174D73" },
      { name: "White", hex: "#F8F8F6" },
    ],
    tags: ["low-top", "classic", "blue"],
    currency: "GHS",
    price: 1190,
    images: [createImage(4, "Harbour Low", "Ocean Blue / White")],
    variants: createVariants(4, 1190, [
      [36, 2],
      [37, 2],
      [38, 4],
      [39, 3],
      [40, 3],
      [41, 1],
      [42, 0],
      [43, 1],
    ]),
    status: "active",
    isFeatured: false,
    isNewArrival: true,
    isDemo: true,
    publishedAt: "2026-07-20T09:00:00.000Z",
  },
  {
    id: "demo-product-05",
    handle: "ridge-union-terrain-one",
    title: "Terrain One",
    brand: "Ridge Union",
    colorway: "Clay / Moss",
    description:
      "A trail-ready profile with reinforced panels, a grippy lugged sole, and muted earth tones for off-road weekends.",
    category: "Trail",
    colors: [
      { name: "Clay", hex: "#A85D3B" },
      { name: "Moss", hex: "#5B6746" },
    ],
    tags: ["trail", "outdoor", "lugged"],
    currency: "GHS",
    price: 1580,
    images: [createImage(5, "Terrain One", "Clay / Moss")],
    variants: createVariants(5, 1580, [
      [39, 1],
      [40, 2],
      [41, 2],
      [42, 4],
      [43, 3],
      [44, 3],
      [45, 1],
      [46, 1],
    ]),
    status: "active",
    isFeatured: true,
    isNewArrival: false,
    isDemo: true,
    publishedAt: "2026-07-08T09:00:00.000Z",
  },
  {
    id: "demo-product-06",
    handle: "afterdark-metro-deck",
    title: "Metro Deck",
    brand: "Afterdark Supply",
    colorway: "Black / Gum",
    description:
      "A durable skate shape with a reinforced toe, cushioned tongue, and classic gum outsole for daily wear.",
    category: "Skate",
    colors: [
      { name: "Black", hex: "#141414" },
      { name: "Gum", hex: "#B37A42" },
    ],
    tags: ["skate", "black", "gum-sole"],
    currency: "GHS",
    price: 1240,
    images: [createImage(6, "Metro Deck", "Black / Gum")],
    variants: createVariants(6, 1240, [
      [38, 0],
      [39, 2],
      [40, 3],
      [41, 4],
      [42, 2],
      [43, 2],
      [44, 1],
      [45, 0],
    ]),
    status: "active",
    isFeatured: false,
    isNewArrival: false,
    isDemo: true,
    publishedAt: "2026-06-29T09:00:00.000Z",
  },
  {
    id: "demo-product-07",
    handle: "aerial-halo-knit",
    title: "Halo Knit",
    brand: "Aerial Dept.",
    colorway: "Silver / Ice",
    description:
      "A flexible knit runner pairing a sock-like fit with lightweight foam and reflective silver accents.",
    category: "Running",
    colors: [
      { name: "Silver", hex: "#AEB5BB" },
      { name: "Ice", hex: "#DDEEF1" },
    ],
    tags: ["runner", "knit", "reflective"],
    currency: "GHS",
    price: 1380,
    images: [createImage(7, "Halo Knit", "Silver / Ice")],
    variants: createVariants(7, 1380, [
      [36.5, 2],
      [37.5, 3],
      [38.5, 2],
      [39.5, 1],
      [40.5, 4],
      [41.5, 2],
      [42.5, 1],
      [43.5, 0],
    ]),
    status: "active",
    isFeatured: false,
    isNewArrival: true,
    isDemo: true,
    publishedAt: "2026-07-18T09:00:00.000Z",
  },
  {
    id: "demo-product-08",
    handle: "block-form-block-90",
    title: "Block 90",
    brand: "Block Form",
    colorway: "Oxblood / Cream",
    description:
      "A retro-inspired street sneaker with bold paneling, a substantial midsole, and rich oxblood detailing.",
    category: "Lifestyle",
    colors: [
      { name: "Oxblood", hex: "#632A2A" },
      { name: "Cream", hex: "#EEE2C9" },
    ],
    tags: ["retro", "street", "panelled"],
    currency: "GHS",
    price: 1490,
    images: [createImage(8, "Block 90", "Oxblood / Cream")],
    variants: createVariants(8, 1490, [
      [38, 1],
      [39, 1],
      [40, 2],
      [41, 0],
      [42, 3],
      [43, 2],
      [44, 2],
      [45, 1],
    ]),
    status: "active",
    isFeatured: true,
    isNewArrival: false,
    isDemo: true,
    publishedAt: "2026-07-04T09:00:00.000Z",
  },
  {
    id: "demo-product-09",
    handle: "courtworks-pivot-pro",
    title: "Pivot Pro",
    brand: "Courtworks",
    colorway: "Violet / Volt",
    description:
      "A quick-cut court sneaker with lateral support, energetic cushioning, and vivid violet and volt accents.",
    category: "Basketball",
    colors: [
      { name: "Violet", hex: "#583F8D" },
      { name: "Volt", hex: "#C9ED3F" },
    ],
    tags: ["court", "performance", "bright"],
    currency: "GHS",
    price: 1720,
    images: [createImage(9, "Pivot Pro", "Violet / Volt")],
    variants: createVariants(9, 1720, [
      [40, 1],
      [41, 2],
      [42, 2],
      [42.5, 3],
      [43, 2],
      [44, 1],
      [45, 2],
      [46, 1],
    ]),
    status: "active",
    isFeatured: true,
    isNewArrival: true,
    isDemo: true,
    publishedAt: "2026-07-26T09:00:00.000Z",
  },
  {
    id: "demo-product-10",
    handle: "ridge-union-slate-trek",
    title: "Slate Trek",
    brand: "Ridge Union",
    colorway: "Slate / Sand",
    description:
      "A weather-minded trail sneaker with protective overlays, a comfortable collar, and a grounded slate palette.",
    category: "Trail",
    colors: [
      { name: "Slate", hex: "#515B62" },
      { name: "Sand", hex: "#C8B99A" },
    ],
    tags: ["trail", "outdoor", "neutral"],
    currency: "GHS",
    price: 1620,
    images: [createImage(10, "Slate Trek", "Slate / Sand")],
    variants: createVariants(10, 1620, [
      [39, 0],
      [40, 1],
      [41, 2],
      [42, 2],
      [43, 3],
      [44, 2],
      [45, 1],
      [46, 0],
    ]),
    status: "active",
    isFeatured: false,
    isNewArrival: false,
    isDemo: true,
    publishedAt: "2026-06-22T09:00:00.000Z",
  },
  {
    id: "demo-product-11",
    handle: "afterdark-night-shift",
    title: "Night Shift",
    brand: "Afterdark Supply",
    colorway: "Midnight / Reflective",
    description:
      "A tonal low-top with subtle reflective hits and an understated shape made for late-night city movement.",
    category: "Lifestyle",
    colors: [
      { name: "Midnight", hex: "#171B25" },
      { name: "Reflective", hex: "#C8CDD1" },
    ],
    tags: ["low-top", "reflective", "tonal"],
    currency: "GHS",
    price: 1350,
    images: [createImage(11, "Night Shift", "Midnight / Reflective")],
    variants: createVariants(11, 1350, [
      [38, 2],
      [39, 2],
      [40, 3],
      [41, 2],
      [42, 4],
      [43, 1],
      [44, 1],
      [45, 1],
    ]),
    status: "active",
    isFeatured: true,
    isNewArrival: true,
    isDemo: true,
    publishedAt: "2026-07-28T09:00:00.000Z",
  },
  {
    id: "demo-product-12",
    handle: "block-form-canvas-grid",
    title: "Canvas Grid",
    brand: "Block Form",
    colorway: "Natural / Ink",
    description:
      "A canvas skate staple with grid-stitched side panels, a cushioned footbed, and a clean natural-and-ink finish.",
    category: "Skate",
    colors: [
      { name: "Natural", hex: "#D9CFB9" },
      { name: "Ink", hex: "#22252A" },
    ],
    tags: ["canvas", "skate", "low-top"],
    currency: "GHS",
    price: 1150,
    images: [createImage(12, "Canvas Grid", "Natural / Ink")],
    variants: createVariants(12, 1150, [
      [36, 1],
      [37, 2],
      [38, 3],
      [39, 2],
      [40, 2],
      [41, 1],
      [42, 1],
      [43, 0],
    ]),
    status: "active",
    isFeatured: false,
    isNewArrival: false,
    isDemo: true,
    publishedAt: "2026-06-15T09:00:00.000Z",
  },
] as const satisfies readonly Product[];

export type DemoProduct = (typeof products)[number];
